[package]
name = "AccountActions"
edition = "2024.beta"
license = "MIT"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.Kiosk]
git = "https://github.com/mcxross/apps.git"
subdir = "kiosk"
rev = "testnet"

[dependencies.AccountProtocol]
local = "../protocol"

[dependencies.AccountConfig]
local = "../config"

[dependencies.AccountExtensions]
local = "../extensions"

[addresses]
account_config = "0x207c6d8ecdc69052e78a531b3475eb3f21128e72ae450f5289df709c4b622cdc"
account_actions = "0x0"
account_protocol = "0x9396f11ad0d098156b9df281013b63303558b8f1a2a681d3d1caf59a2f873c28"
account_extensions = "0xaa599a03695b5b14c21a81b5050a7644c81db38f8ba57a185df13f57f237aa33"
kiosk = "0x332ba1a4ca0d435c88a7a87c7eaf57ae526df0cdd81294be885ebacc485aef63"
